# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/alexy/Documents/unreal-engine-5.4.1
GAMEPROJECTFILE =/home/alexy/dev/weeksauce/weeksauce.uproject

TARGETS = \
	weeksauce-Linux-DebugGame  \
	weeksauce-Linux-Shipping  \
	weeksauce \
	weeksauceEditor-Linux-DebugGame  \
	weeksauceEditor-Linux-Shipping  \
	weeksauceEditor \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Shipping  \
	UnrealGame\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend weeksauceEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug weeksauceEditor-Linux-Debug


weeksauce-Linux-DebugGame:
	 $(PROJECTBUILD) weeksauce Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

weeksauce-Linux-Shipping:
	 $(PROJECTBUILD) weeksauce Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

weeksauce:
	 $(PROJECTBUILD) weeksauce Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

weeksauceEditor-Linux-DebugGame:
	 $(PROJECTBUILD) weeksauceEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

weeksauceEditor-Linux-Shipping:
	 $(PROJECTBUILD) weeksauceEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

weeksauceEditor:
	 $(PROJECTBUILD) weeksauceEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
