name: Format check on pull request
on: pull_request

permissions:
  contents: read

jobs:
  dotnet-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Test
        run: ls -al

      - name: Format
        run: dotnet format --verify-no-changes --verbosity diagnostic weeksauce-linux.sln
