name: Linting validation (clang-tidy)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  clang-tidy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Project
      uses: actions/checkout@v2

    - name: Setup clang
      uses: llvm/llvm-project@main
      with:
        version: '14'

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-tidy cmake

    - name: Run clang-tidy
      run: |
        make lint-ci

    - name: Upload clang-tidy Report
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: clang-tidy-report
        path: clang-tidy-output.log
